### ISSUE TITLE
[Bug Fix] Fix broken link in Index page

### ISSUE THREAD

**Issue by carlosrrdev** [carlosrrdev/wonder-destinations#12]
## Current Behavior

Clicking on the brand logo in the `nav` does nothing.
```html
<div>
  <a href="#">
    <img src="./assets/images/Wonder_Destinations.png" width="200" height="" />
  </a>
</div>
```
> You have a `height` attribute on the image, but you are not using it. Consider removing any unused attributes

## Expected Behavior

Clicking on the brand logo in the `nav` should take users to the `index.html` page.
```html
<div>
  <a href="index.html"> <!-- added link to the index page -->
    <img src="./assets/images/Wonder_Destinations.png" width="200" />
  </a>
</div>
```

This change will need to be applied to the `nav` of each page.

**Comment by nkirti28** [comment]
removed unused attribute "height" from navbar
